# Generated by Django 3.2.5 on 2021-09-10 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_auto_20210909_2103'),
        ('animelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeentry',
            name='airing_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='alt_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='anime_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='genres',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='members',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='popularity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='ranked',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='source',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='studio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='t_eps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='userp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.userprofile'),
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='comments',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='eps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='mal_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='picture',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='prio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='rewatched',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='rewatching',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
