# Generated by Django 3.2.5 on 2021-09-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animelist', '0002_auto_20210909_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeentry',
            name='desc',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
