# Generated by Django 3.2.5 on 2021-09-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animelist', '0003_animeentry_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeentry',
            name='rating',
        ),
        migrations.AddField(
            model_name='animeentry',
            name='mean',
            field=models.FloatField(null=True),
        ),
    ]
