# Generated by Django 3.2.5 on 2021-09-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20210908_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_mal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_mdx',
            field=models.BooleanField(default=False),
        ),
    ]
