# Generated by Django 3.2.5 on 2021-09-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangalist', '0001_initial'),
        ('animelist', '0001_initial'),
        ('signup', '0005_auto_20210909_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anime_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animelist.animeentry'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manga_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mangalist.mangaentry'),
        ),
    ]
